### ISSUE TITLE
Raspberry Pi Zero support

### ISSUE THREAD

**Issue by zoolyka** [servall/pi-camera-connect#10]
Please add support for the Pi Zero (W), just have to extend the `systemInfo.model` detection in `still-camera.js` and `stream-camera.js` with:

```
case 'BCM2835 - Pi Zero':
case 'BCM2835 - Pi Zero W':
```

It uses the same chipset, and works great with your library.

Thank you.

**Comment by ChristiaanHaas** [comment]
Because I had the same issue, I opened a pull request to fix this! 
https://github.com/servall/pi-camera-connect/pull/13

**Comment by gregnr** [comment]
#13 is now merged. Thanks for the issue @zoolyka and PR @ChristiaanHaas.
