### ISSUE TITLE
Stream over socket.io?

### ISSUE THREAD

**Issue by EddieOne** [servall/pi-camera-connect#3]
I was thinking of base64, maybe there is a better way?

I'm currently saving an image repeatedly and reloading on the client. It doesn't work very well.

**Comment by gregnr** [comment]
Hi @EddieOne thanks for the question and sorry for the delay. I know this has been done before but couldn't tell you off the top of my head the best way to do it. Give me a bit of time to ask around and I'll follow up with you.

**Comment by der-ule** [comment]
I am currently using this snipped to do that:

in server:
```
streamCamera.on('frame', (data)=>{
    io.emit('image', "data:image/jpeg;base64,"+ data.toString("base64"));
});
```
in HTML:
```
      socket.on('image', (data) => {
        const imageElm = document.getElementById('image');
        imageElm.src = data;
      });
```
it works good.

**Comment by EddieOne** [comment]
One thing I tried was telling the client when the image was updated. This also worked well, with a little flickering. The base64 way looks like it would always transmit everything. Thank you, for the example.
