### ISSUE TITLE
Photo and video not working

### ISSUE THREAD

**Issue by aaronledesma** [servall/pi-camera-connect#30]
I paste the exactly code and this just stay for ever waiting
![foto](https://user-images.githubusercontent.com/59378626/111422198-84c58980-86ab-11eb-8b88-e600f62ccdd5.png)

**Comment by gregnr** [comment]
Hi @aaronledesma, thanks for the issue. Can you confirm that the following command successfully takes a photo?
```bash
raspistill -o photo.jpg
```
And this takes a video:
```bash
raspivid -o video.h264 -t 10000
```

**Comment by aaronledesma** [comment]
Yes, that works great!
